"""Rename password column

Revision ID: 07de541a9388
Revises: 74cbdb53ec0f
Create Date: 2026-07-10 19:39:47.041292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07de541a9388'
down_revision: Union[str, Sequence[str], None] = '74cbdb53ec0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('encrypted_password', sa.String(length=255), nullable=False))
    op.drop_column('servers', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('servers', 'encrypted_password')
    # ### end Alembic commands ###
