"""Create monitoring snapshots

Revision ID: 34a27c978872
Revises: c5d8f25dfe6f
Create Date: 2026-07-12 15:37:20.342790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a27c978872'
down_revision: Union[str, Sequence[str], None] = 'c5d8f25dfe6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('disk_usage', sa.Float(), nullable=False),
    sa.Column('load_average', sa.Float(), nullable=False),
    sa.Column('network_rx', sa.BigInteger(), nullable=False),
    sa.Column('network_tx', sa.BigInteger(), nullable=False),
    sa.Column('uptime_seconds', sa.BigInteger(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_snapshots_collected_at'), 'monitoring_snapshots', ['collected_at'], unique=False)
    op.create_index(op.f('ix_monitoring_snapshots_server_id'), 'monitoring_snapshots', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_snapshots_server_id'), table_name='monitoring_snapshots')
    op.drop_index(op.f('ix_monitoring_snapshots_collected_at'), table_name='monitoring_snapshots')
    op.drop_table('monitoring_snapshots')
    # ### end Alembic commands ###
